server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
      - id: optimus-auth
        uri: lb://optimus-auth
        predicates:
        - Path=/oauth/token
        filters:
        - EncryptPassword
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
gateway:
  whitelist:
    - /optimus-auth/oauth/token