server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
        optimus-basic-service:
              path: /basic-service/**
              serviceId: optimus-basic-service
              stripPrefix: true
              sensitiveHeaders: