server:
  port: 8081
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
gateway:
  whitelist:
    - /optimus-auth/oauth/token
  greylist:
    - /optimus-auth/oauth/removeToken