server:
  port: 8088
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/optimus_oauth?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ENC(3Rryn6cUlnKz/0F2KQ//sA==)
      password: ENC(vb29azSqoas6eebkSr0IzQ==)
swagger:
  title: 基础服务
  description: 用户管理, 组织管理，角色管理，接口管理
  url: https://github.com/shanks-devil/optimus/tree/master/optimus-basic-service
  version: 1.0
  enable: true